-- Generated by Oracle SQL Developer Data Modeler 19.1.0.081.0911
--   at:        2019-06-18 15:13:51 EDT
--   site:      SQL Server 2012
--   type:      SQL Server 2012



CREATE TABLE cleaners (
    idcleaner       NUMERIC(10) NOT NULL,
    fcleanername    VARCHAR(50) NOT NULL,
    mcleanername    VARCHAR(50),
    lcleanername    VARCHAR(50) NOT NULL,
    claddress       VARCHAR(60),
    claddressunit   VARCHAR(15),
    clpostalcode    VARCHAR(6),
    clcity          VARCHAR(25),
    clprovince      VARCHAR(2),
    clphone1        VARCHAR(14),
    clphone2        VARCHAR(14),
    clsincnumber    VARCHAR(9),
    username        VARCHAR(40) NOT NULL
)

go 

    


CREATE unique nonclustered index cleaners_idx ON cleaners ( idcleaner )

ALTER TABLE Cleaners ADD constraint cleaners_pk PRIMARY KEY CLUSTERED (IdCleaner)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON ) 

CREATE TABLE cleanersrate (
    idrate        NUMERIC(10) NOT NULL,
    idschedule    NUMERIC(10) NOT NULL,
    idcleaner     NUMERIC(10) NOT NULL,
    cleanerrate   VARCHAR(10) NOT NULL
)


CREATE unique nonclustered index cleanersrate_idx ON cleanersrate ( idrate ) 

ALTER TABLE CleanersRate ADD constraint cleanersrate_pk PRIMARY KEY CLUSTERED (IdRate)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON ) 

CREATE TABLE customeraddress (
    idcustaddress   NUMERIC(10) NOT NULL,
    idcustomer      NUMERIC(10) NOT NULL,
    address         VARCHAR(50),
    addressunit     VARCHAR(15),
    postalcode      VARCHAR(6),
    city            VARCHAR(25),
    province        VARCHAR(2)
)


    
CREATE unique nonclustered index customeraddress_idx ON customeraddress ( idcustaddress ) 

ALTER TABLE CustomerAddress ADD constraint customeraddress_pk PRIMARY KEY CLUSTERED (IdCustAddress)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON ) 

CREATE TABLE customers (
    idcustomer      NUMERIC(10) NOT NULL,
    fcustomername   VARCHAR(50) NOT NULL,
    mcustomername   VARCHAR(50),
    lcustomername   VARCHAR(50) NOT NULL,
    ctphone1        VARCHAR(14),
    ctphone2        VARCHAR(14),
    username        VARCHAR(40) NOT NULL
)

    
CREATE unique nonclustered index customers_idx ON customers ( idcustomer ) 

ALTER TABLE Customers ADD constraint customers_pk PRIMARY KEY CLUSTERED (IdCustomer)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON ) 

CREATE TABLE customersubscription (
    idsubscription   NUMERIC(10) NOT NULL,
    idcustomer       NUMERIC(10) NOT NULL,
    subscription     CHAR(1),
    periodicity      VARCHAR(10),
    finishdate       datetime
)


   
CREATE unique nonclustered index customersubscription_idx ON customersubscription ( idsubscription ) 

ALTER TABLE CustomerSubscription ADD constraint customersubscription_pk PRIMARY KEY CLUSTERED (IdSubscription)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON ) 

CREATE TABLE schedule (
    idschedule             NUMERIC(10) NOT NULL,
    idserviceprice         NUMERIC(10) NOT NULL,
    idcustomer             NUMERIC(10) NOT NULL,
    ctdaterequestservice   datetime,
    ctaddress              VARCHAR(100) NOT NULL,
    cthoursrequested       NUMERIC(3),
    idcleaner              NUMERIC(10) NOT NULL,
    clockin                datetime,
    clockout               datetime,
    idcustaddress          NUMERIC(10) NOT NULL
)


CREATE unique nonclustered index schedule_idx ON schedule ( idschedule ) 

ALTER TABLE Schedule ADD constraint schedule_pk PRIMARY KEY CLUSTERED (IdSchedule)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON ) 

CREATE TABLE schedulepayment (
    idschedulepayment      NUMERIC(10) NOT NULL,
    idschedule             NUMERIC(10) NOT NULL,
    idcustomer             NUMERIC(10) NOT NULL,
    cthourscontracted      NUMERIC(2),
    paidbycustomer         CHAR(1) DEFAULT 'N',
    amountpaidbycustomer   NUMERIC(10, 2),
    idcleaner              NUMERIC(10) NOT NULL,
    paidtocleaner          CHAR(1) DEFAULT 'N',
    clhoursworked          NUMERIC(2),
    amountpaidtocleaner    NUMERIC(10, 2)
)


ALTER TABLE SchedulePayment 
    ADD 
    CHECK ( paidByCustomer IN ('N', 'Y') ) 

ALTER TABLE SchedulePayment 
    ADD 
    CHECK ( paidToCleaner IN ('N', 'Y') ) 


CREATE unique nonclustered index schedulepayment_idx ON schedulepayment ( idschedulepayment ) 

ALTER TABLE SchedulePayment ADD constraint schedulepayment_pk PRIMARY KEY CLUSTERED (IdSchedulePayment)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON ) 

CREATE TABLE serviceprice (
    idserviceprice   NUMERIC(10) NOT NULL,
    ctamounthour     NUMERIC(8, 2) NOT NULL,
    clamounthour     NUMERIC(8, 2)
)

    
CREATE unique nonclustered index serviceprice_idx ON serviceprice ( idserviceprice ) 

ALTER TABLE ServicePrice ADD constraint serviceprice_pk PRIMARY KEY CLUSTERED (IdServicePrice)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON ) 

CREATE TABLE userlogin (
    username   VARCHAR(40) NOT NULL,
    pin        VARCHAR(8) NOT NULL,
    role       VARCHAR(15) NOT NULL
)


ALTER TABLE userlogin add check(role IN(
    'CLEANER', 'CUSTOMER', 'MANAGER'
)) 

ALTER TABLE UserLogin ADD constraint userlogin_pk PRIMARY KEY CLUSTERED (Username)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON ) 

ALTER TABLE Cleaners
    ADD CONSTRAINT cleaners_userlogin_fk FOREIGN KEY ( username )
        REFERENCES userlogin ( username )
ON DELETE NO ACTION 
    ON UPDATE no action 

ALTER TABLE CleanersRate
    ADD CONSTRAINT cleanersrate_cleaners_fk FOREIGN KEY ( idcleaner )
        REFERENCES cleaners ( idcleaner )
ON DELETE NO ACTION 
    ON UPDATE no action 

ALTER TABLE CleanersRate
    ADD CONSTRAINT cleanersrate_schedule_fk FOREIGN KEY ( idschedule )
        REFERENCES schedule ( idschedule )
ON DELETE NO ACTION 
    ON UPDATE no action 

ALTER TABLE CustomerAddress
    ADD CONSTRAINT customeraddress_customers_fk FOREIGN KEY ( idcustomer )
        REFERENCES customers ( idcustomer )
ON DELETE NO ACTION 
    ON UPDATE no action 

ALTER TABLE Customers
    ADD CONSTRAINT customers_userlogin_fk FOREIGN KEY ( username )
        REFERENCES userlogin ( username )
ON DELETE NO ACTION 
    ON UPDATE no action 

ALTER TABLE CustomerSubscription
    ADD CONSTRAINT customersubscription_customers_fk FOREIGN KEY ( idcustomer )
        REFERENCES customers ( idcustomer )
ON DELETE NO ACTION 
    ON UPDATE no action 

ALTER TABLE Schedule
    ADD CONSTRAINT schedule_cleaners_fk FOREIGN KEY ( idcleaner )
        REFERENCES cleaners ( idcleaner )
ON DELETE NO ACTION 
    ON UPDATE no action 

ALTER TABLE Schedule
    ADD CONSTRAINT schedule_customeraddress_fk FOREIGN KEY ( idcustaddress )
        REFERENCES customeraddress ( idcustaddress )
ON DELETE NO ACTION 
    ON UPDATE no action 

ALTER TABLE Schedule
    ADD CONSTRAINT schedule_customers_fk FOREIGN KEY ( idcustomer )
        REFERENCES customers ( idcustomer )
ON DELETE NO ACTION 
    ON UPDATE no action 

ALTER TABLE Schedule
    ADD CONSTRAINT schedule_serviceprice_fk FOREIGN KEY ( idserviceprice )
        REFERENCES serviceprice ( idserviceprice )
ON DELETE NO ACTION 
    ON UPDATE no action 

ALTER TABLE SchedulePayment
    ADD CONSTRAINT schedulepayment_cleaners_fk FOREIGN KEY ( idcleaner )
        REFERENCES cleaners ( idcleaner )
ON DELETE NO ACTION 
    ON UPDATE no action 

ALTER TABLE SchedulePayment
    ADD CONSTRAINT schedulepayment_customers_fk FOREIGN KEY ( idcustomer )
        REFERENCES customers ( idcustomer )
ON DELETE NO ACTION 
    ON UPDATE no action 

ALTER TABLE SchedulePayment
    ADD CONSTRAINT schedulepayment_schedule_fk FOREIGN KEY ( idschedule )
        REFERENCES schedule ( idschedule )
ON DELETE NO ACTION 
    ON UPDATE no action 



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             9
-- CREATE INDEX                             8
-- ALTER TABLE                             25
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE DATABASE                          0
-- CREATE DEFAULT                           0
-- CREATE INDEX ON VIEW                     0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE ROLE                              0
-- CREATE RULE                              0
-- CREATE SCHEMA                            0
-- CREATE SEQUENCE                          0
-- CREATE PARTITION FUNCTION                0
-- CREATE PARTITION SCHEME                  0
-- 
-- DROP DATABASE                            0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
